### ISSUE TITLE
use of plugin causes error / typo3 9.5.9/10

### ISSUE THREAD

**Issue by asche76** [Hauer-Heinrich/hh_slider#1]
use of plugin (Slider [hhslider_hh_slider]) as page content causes error in normal backend page view  / typo3 9.5.9/10. with list view it works. frontend output works fine.

`(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file (Standard/Index.html). No paths configured.

in /var/customers/webs/customer1/vendor/typo3fluid/fluid/src/View/TemplatePaths.php line 598
        }
        $templateReference = $this->resolveTemplateFileForControllerAndActionAndFormat($controller, $action);
        if (!file_exists($templateReference) && $templateReference !== 'php://stdin') {
            $format = $this->getFormat();
            throw new InvalidTemplateResourceException(
                sprintf(
                    'Tried resolving a template file for controller action "%s->%s" in format ".%s", but none of the paths ' .
                    'contained the expected template file (%s). %s',
                    $controller,`

and so on...

**Comment by Teisi** [comment]
TYPO3 10 is not testet yet.

On TYPO3 9.5.8 - 9.5.9 - 9.5.10 with PHP 7.2 i can't reproduce this.

Can you give us more information about your system?

Slider version, PHP version, other extensions you are using etc...

**Comment by medarob** [comment]
I have the same problem in TYPO3 9.5.10 with PHP 7.2.23.

I installed the extension via composer and added the plugin with 3 images only, saved it and the backend was broken. Frontend works.
![grafik](https://user-images.githubusercontent.com/33951787/67262191-268b7b80-f4a4-11e9-9195-804dec823336.png)

In order to be able to remove the CE I had to deactivate the extension. Now the backend works again but I can't use the extension.

**Comment by medarob** [comment]
I found some related articles, maybe that helps?

https://github.com/FluidTYPO3/flux/issues/1691
https://wiki.typo3.org/Exception/CMS/1257246929
https://github.com/FluidTYPO3/fluidpages/issues/409

**Comment by Teisi** [comment]
ok thank you, with non composer mode / no flux ext - there is no problem. So i think this is not a issue of hh_slider extension but i try to reproduce this at my pc and look if i can do something :)

**Comment by ineswillenbrock** [comment]
I got the same error but (hopefully) fixed it by including the TS Template into the site root, not the page where the slider should be shown.

**Comment by Teisi** [comment]
So i have now TYPO3 9.5.11 (composer) and fluidtypo3/flux 9.2 installed, but i can't reproduce this issue - can someone give me more information about how to reproduce this?

**Comment by asche76** [comment]
- same issue as before (t3 9.5.11, t3sbootstrap 4.3.6). it doesn't matter if the plugin + static ts on the same page or not. every backend page with the plugin causes that error.
![hh_slider](https://user-images.githubusercontent.com/47745128/68765265-b0021980-061c-11ea-8318-afb22315d909.png)

- another thing ist, that the slider doesn't respect cropped images

**Comment by asche76** [comment]
here's the complete issue list from the backend:
[hh_slider_issues.docx](https://github.com/Hauer-Heinrich/hh_slider/files/3841168/hh_slider_issues.docx)

**Comment by ineswillenbrock** [comment]
Fresh install of TYPO3 9.5.11 with Introduction Package and hh_slider 0.1.4 says:
With setting the TypoScript in the template but without setting the TypoScript on the page:
![Screenshot_20191113_152050](https://user-images.githubusercontent.com/44277221/68772141-961b0380-0629-11ea-828d-fa0be5bfab1e.png)

If I add the TypoScript of the Extension to the page (Edit page -> Ressources) the page with the slider is shown. And survives deleting the content of typo3temp.

**Comment by Teisi** [comment]
@ineswillenbrock yes this looks right, cause of the paths are written in that pageTS. So you have the choice if you would like to use this default template or your own (so no overwrite is needed) or you use the default one and overwrite it.

@asche76 ok with composer or without? I try to get an installation with your versions (t3 9.5.11, t3sbootstrap 4.3.6).

EDIT: @asche76 i see, t3sbootstrap works only without composer... - i have this issue only if i don't include the pageTS for the slider (page settings -> resources)

**Comment by Teisi** [comment]
New version 0.1.5 - now you can add the typoscript (setup and constants) and pagets automatically, so you don't need to include it manually.
Go to the backend -> settings-module -> extension configuration -> hh_slider.
Default this is disabled to not break someone's installation.

**Comment by asche76** [comment]
> EDIT: @asche76 i see, t3sbootstrap works only without composer... - i have this issue only if i don't include the pageTS for the slider (page settings -> resources)

confirmed: with pageTS from resources it works

**Comment by Teisi** [comment]
So this can be closed, yes? :)

**Comment by medarob** [comment]
I just tried v1.6 and the backend is still broken :/

edit: with `Go to the backend -> settings-module -> extension configuration -> hh_slider` the backend seems to work now :)
