### ISSUE TITLE
exclude webm video from an extra video tag if mp4 with the same name is already available

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#10]
I tried the folder option and noticed the following two bugs:

I have a folder with 2 video files: teaser.**mp4** and teaser.**webm**
Furthermore I have a responsive option which should show 4 slides at a particular breakpoint.

Now, if I use the slider by folder content option multiple video tags are added, one tag with only the webm file and on tag with both, the mp4 and webm file:

```
<div class="slider-container slider-container-7585  tns-slider tns-carousel tns-subpixel tns-calc tns-horizontal" id="tns2" style="transform: translate3d(-25%, 0px, 0px); transition-duration: 0s;">
    <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item" aria-hidden="true" tabindex="-1">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
    </video>
    <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
        <source src="/fileadmin/videos/teaser.mp4" type="video/mp4">
    </video>
    <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
    </video>
    <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active" id="tns2-item0">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
        <source src="/fileadmin/videos/teaser.mp4" type="video/mp4">
     </video>
     <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active" id="tns2-item1">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
     </video>
     <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
        <source src="/fileadmin/videos/teaser.mp4" type="video/mp4">
     </video>
     <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item tns-slide-active">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
     </video>
     <video playsinline="" muted="" loop="" controls="" no-cookie="" preload="" class="video-embed-item tns-item" aria-hidden="true" tabindex="-1">
        <source src="/fileadmin/videos/teaser.webm" type="video/webm">
        <source src="/fileadmin/videos/teaser.mp4" type="video/mp4">
     </video>
</div>
```
The extra video tag with only the webm file is not necessary because it's already included as a second source in video tag with that mp4 file.

=> Therefore it's better to exclude the video tag with only the webm video by default and if really necessary make an option to include the webm video as separate video tag in the slider.

As said, I configured a responsive option which should show 4 items/videos in desktop mode at a certain breakpoint.
Because of this option I end up with the same video multiple times.

=> Maybe it's possible to check if the minimum number of files/videos is available to create the slider with arrows. If you have only 1 or 2 videos, adding the same video multiple times makes no sense. In that case the slider should only have 1 or 2 slides and shouldn't be scrollable. However, if you change the view and look at the slider on a smartphone (where you have maybe configured that only 1 slide should be shown) then you should be able to scroll if you have 2 files/videos.

**Comment by Teisi** [comment]
This is related to the EXT:hh_video_extender which automatically merges video src...
Please update both extensions. hh_slider 0.1.63 and hh_video_extender 0.1.62.
