### ISSUE TITLE
[feature] responsive configuration should be configurable via the backend options

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#13]
Right now it's only possible to define a fixed numer of slides which then shows up in the frontend. This number is valid for all breakpoint/resolution.
If you want to have 4 slides to display at once in the frontend you can set the "Slides per view" option to 4 and that will work on desktop resolutions but also effects the smartphone resolutions. But there you normally want to have fewer slides, maybe only 2 or 1 slide.

To make that work, you can add the `responsive` option to the JSON partial file, for example:
`"responsive": {"640": {"edgePadding": 20,"gutter": 20,"items": 2},"992": {"edgePadding": 30,"items": 3},"1200": {"edgePadding": 40,"items": 4}},`

There you can add multiple breakpoints and the number of items to display. 

The problem is, that this option does not exists in the backend and therfore is not configurable and a fixed option for all sliders on the website will be used.
This option might work for an image- or videoslider but if you want to add a banner slider with only one image at a time this won't work. Because of the fixed `resolution` options in the JSON partial you will end up with 4 banner pictures at once.

Therefore, the `resolution` option should be configurable in the backend to make different sliders on the website more adjustable. The 'Slides per view' option can then be used to set the number of slides for the smartphone resolution only and for all other breakpoints you use the breakpoint option.

Maybe it's possible to add an IRRE field where you can add breakpoints and to each breakpoint you can add options which the tinyslider supports for the resolution option like `items`, `gutter`, etc.

**Comment by Teisi** [comment]
Same request like #7
