### ISSUE TITLE
[bug] error messages in Template module that setup.typoscript and constants.typoscript are missing

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#15]
If I go to the Template module there is the following error for setup and constants:

**Setup:**

![grafik](https://user-images.githubusercontent.com/33951787/83633959-04adb780-a5a2-11ea-99db-dbf502fd506e.png)

**Constants:**

![grafik](https://user-images.githubusercontent.com/33951787/83634017-2313b300-a5a2-11ea-974a-45334af5b2c7.png)

I use the automatic typoscript integration in the extension settings because otherwise I still get an error that Typoscript would be missing:

![grafik](https://user-images.githubusercontent.com/33951787/83634209-6e2dc600-a5a2-11ea-8965-5eddc666c3cd.png)

The slider in general works but I don't know if these error messages are correct and if it's related to the other issue here: https://github.com/Hauer-Heinrich/hh_slider/issues/1

**Comment by Teisi** [comment]
Which TYPO3 version do you use? Which hh_slider version?

**Comment by medarob** [comment]
I use TYPO3 9.5.21.

I have another idea that I have to check out. I recently learned that the load order of the extensions in the packagestate.php is also important. So I have to check the dependencies if they are correct. Maybe that will solve the issue but this is just a guess.

**Comment by medarob** [comment]
I think the problem is in the ext_tables.php file

```
        // Add Constants
        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptConstants(
            '<INCLUDE_TYPOSCRIPT: source="FILE:EXT:'.$extensionKey.'/Configuration/Typoscript/constants.typoscript">'
        );

        // Add Setup
        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup(
            '<INCLUDE_TYPOSCRIPT: source="FILE:EXT:'.$extensionKey.'/Configuration/Typoscript/setup.typoscript">'
        );
```

Both path names are incorrect. "Typoscript" should be "TypoScript" with a captial letter S:

=> /Configuration/Typo**S**cript/constants.typoscript
=> /Configuration/Typo**S**cript/setup.typoscript

I changed it temporarily and the error was gone.

**Comment by Teisi** [comment]
@medarob aahhhh thank you ... 
this is the disadvantage of working on windows such errors are rather hard to find - at least for me... :)
I hope this will be solved after I have migrated the whole environment to the WSL... thank you
