### ISSUE TITLE
"Centered Slides" option not working?

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#17]
Hi,

I enabled the "Centered Slides" option but the slides are not centered.

FE:
![grafik](https://user-images.githubusercontent.com/33951787/87528498-e1405700-c68d-11ea-9f42-c7ab87f0fc94.png)

BE:
![grafik](https://user-images.githubusercontent.com/33951787/87528574-f917db00-c68d-11ea-9491-068e8e9dbb79.png)

I disabled all custom CSS.

Can someone confirm the issue on the latest version 0.2?
I think it worked before but not sure why it now does not work 🤔

**Comment by medarob** [comment]
It seems to work only if `Slides per View` is greater than 1.

If you have only 1 slide per view you have to add
```
div.tns-item{
    text-align:center;
}
```
source: https://stackoverflow.com/questions/56890573/tiny-slider-not-centering-images-properly

Maybe this can be added as default CSS to the hh-slider SCSS?
There seems to be no negative effect if you change the value of `Slides per View` to a value greater than 1.

**Comment by Teisi** [comment]
@medarob the option "Centered Slides" has no effect on the position of the content, only on the container of the slider-item (single) if several slider-items are displayed - i.e. if "Slides per view" > 1.

Accordingly, this is not a bug or anything like that.
What happens to the content of a slider item is a custom thing.
