### ISSUE TITLE
Linked images

### ISSUE THREAD

**Issue by ineswillenbrock** [Hauer-Heinrich/hh_slider#2]
Content of the slider: images:
If I add a link to the image, the image is not linked
Content of the slider: content, type images:
The image is linked to the link

I feel like the slider with images should be linked, too.

TYPO3: 9.5.11
hh_slider 0.1.3

**Comment by Teisi** [comment]
Thank you, i look at it :)

**Comment by Teisi** [comment]
Should be fixed with version 0.1.4.
Can you confirm this, please?

**Comment by ineswillenbrock** [comment]
TYPO3 9.5.11, hh_slider 0.1.6: Works for me, thanks!
