### ISSUE TITLE
"Number of slides going on one "click"=1

### ISSUE THREAD

**Issue by stpink** [Hauer-Heinrich/hh_slider#27]
Beim Einbinden von Content, trotz "Number of slides going on one "click"=1", erfolgt der Slide nicht auf den nächsten, sondern slidet bis zum übernächsten Content-Element.

**Comment by Teisi** [comment]
Thank you for your report!

Yes not quite, the autoplay timer did not stop when click on next-prev-button, see:
https://github.com/ganlanyuan/tiny-slider/issues/373

So should be fixed now, do you like to test this on your end with the current GitHub master version? :)

------
And please report issues in english, so everyone can benefit from it, thanks ;)
