### ISSUE TITLE
[Feature Request] option for custom pagination placement

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#3]
Hi,

the default placement of the pagination is below the slider. Maybe it's possible to add an option so that the pagination can be displayed inside the slider at the bottom of the images?

**Comment by Teisi** [comment]
I will look at this.
In the meantime, you can copy the FLUID template and adapt it to your wishes. So you can place the pagination wherever you want. :)

**Comment by Teisi** [comment]
@medarob have forgotten: you can set the position of the elements with css "Flexbox" or "Grid" :)

Edit:
I think this can be done via CSS so everyone can customize this according to their needs.
if someone else is of the opinion, feel free to reopen this ticket :)
