### ISSUE TITLE
arrowKeys option does not work as expected when changed in the responsive options

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#30]
Hi,

I have a slider element with 2 videos and I want that arrows are shown in the mobile view so you can switch between the left and right video via the arrows but from a certain breakpoint on I want to show both videos without the arrows.

That's my backend configuration:
![grafik](https://user-images.githubusercontent.com/33951787/192216752-3e71f410-4446-4d84-8277-07c9ea656321.png)

Initially, show 1 video (slides per view -> works) and show arrows (Arrow enabled -> works).
From 640px upwards show 2 videos (`"items":2` -> works) and disable arrows (`"arrowKeys":false` -> doesn't work).

Result: the two arrows are still visible past the 640px breakpoint.

I also tried the other way, disable the arrows from the beginning and then tried to enable them via the responsive breakpoints and disable them again but that didn't work either.

Is this an error in overriding some of the responsive options?
Can you reproduce the error?

**Comment by Teisi** [comment]
@medarob 
Oh "arrowKeys" refer to the keyboard.
You would probably need something like:
"prevButton": "", "nextButton": ""
unfortunately this doesn't seem to work in my tests - would probably be a bug of the tinyslider itself...
However, if you hide the arrows via CSS from your desired screen size, you will have the same effect. :)

See:
https://github.com/ganlanyuan/tiny-slider
