### ISSUE TITLE
[BUG] Slides not rendered with Content type 'content'

### ISSUE THREAD

**Issue by bh-teufels** [Hauer-Heinrich/hh_slider#37]
Using hh_slider with Content type 'content' the slides (e.g. 2 Text&Media CE's) are not rendered in the FE

**FE Output:**
```
<div id="c30" class="hh-slider frame 0 frame-default frame-type-hhslider_hh_slider frame-layout-0">
    <div class="slider-container slider-container-30">
    </div>
    <span class="slider-button slider-button-prev"></span>
    <span class="slider-button slider-button-next"></span>
</div>
```

**Environment:**
TYPO3 12.4.2
PHP 8.2.2
hh_slider 0.4.2

**Comment by Teisi** [comment]
Thank you for reporting! Should be fixed with 0.4.3 - pushed to TER in view minutes
