### ISSUE TITLE
Embedded content appears twice in the hh_slider

### ISSUE THREAD

**Issue by stpink** [Hauer-Heinrich/hh_slider#44]
I'm trying to use the hh_slider version 0.4.4 for Typo3 12.4.7. 
I'm embedding content using the 'Insert Record' feature of Typo3 in the hh_slider. 
However, the content I embed in the hh_slider appears twice."

**Comment by Teisi** [comment]
haven't forgotten that, just can't get around to checking it at the moment - it's on the to-do list

**Comment by Teisi** [comment]
@stpink how many content-elements have you included?

**Comment by stpink** [comment]
It appears twice only when one content is included.

**Comment by Teisi** [comment]
@stpink ah yes, I should deactivate the slider if only one element is given -> bug.... Thanks for reporting

**Comment by Teisi** [comment]
@stpink would you checkout the new Version 0.4.5?
After Update the Extension, don't forget to use the TYPO3 UpgradeWizard (Install-Tool)

**Comment by stpink** [comment]
Thank's a lot. Now it works fine.
